
export const products = [
  {
    id: '1',
    name: 'Odisha Ikat Handloom Fabric',
    artisanName: 'Prakash Mohanty',
    description: 'Traditional warp and weft tie-dye technique for a unique geometric pattern. Soft cotton-silk blend.',
    category: 'Weave',
    region: 'Odisha',
    price: 2499,
    type: 'Textiles',
    image: {
      src: 'https://picsum.photos/seed/1/300/300',
      hint: 'ikat fabric',
    },
  },
  {
    id: '2',
    name: 'Lord Jagannath Pattachitra',
    artisanName: 'Anaya Das',
    description: 'Scroll painting from Odisha, depicting mythological stories. Finished with natural lacquer.',
    category: 'Painting',
    region: 'Odisha',
    price: 1899,
    type: 'Paintings',
    image: {
      src: 'https://picsum.photos/seed/2/300/300',
      hint: 'pattachitra art',
    },
  },
  {
    id: '3',
    name: 'Channapatna Wooden Toy Set',
    artisanName: 'Ravi Kumar',
    description: 'Traditional lacquerware toys from Karnataka. Non-toxic, eco-friendly, and heirloom quality.',
    category: 'Lacquer',
    region: 'Karnataka',
    price: 850,
    type: 'Jewelry', // Should be toys, but mapping to Jewelry for tab
    image: {
      src: 'https://picsum.photos/seed/3/300/300',
      hint: 'wooden toy',
    },
  },
    {
    id: '4',
    name: 'Gujarati Bandhani Silk Saree',
    artisanName: 'Meera Patel',
    description: 'Finely tied-and-dyed silk saree, known for its bright colors and intricate patterns. From Gujarat.',
    category: 'Tie-Dye',
    region: 'Gujarat',
    price: 4500,
    type: 'Textiles',
    image: {
      src: 'https://picsum.photos/seed/4/300/300',
      hint: 'bandhani saree',
    },
  },
  {
    id: '5',
    name: 'Jaipur Blue Pottery Vase',
    artisanName: 'Sanjay Sharma',
    description: 'Traditional blue pottery, handmade with quartz stone powder, not clay. Classic floral motif.',
    category: 'Ceramic',
    region: 'Rajasthan',
    price: 2800,
    type: 'Pottery',
    image: {
      src: 'https://picsum.photos/seed/5/300/300',
      hint: 'blue pottery',
    },
  },
  {
    id: '6',
    name: 'Assam Cane & Bamboo Basket',
    artisanName: 'Bina Devi',
    description: 'Handwoven storage basket made from sustainable cane and bamboo. Durable and multi-purpose.',
    category: 'Weave',
    region: 'Assam',
    price: 1750,
    type: 'Textiles',
    image: {
      src: 'https://picsum.photos/seed/6/300/300',
      hint: 'bamboo basket',
    },
  },
];
