
export const products = [
  {
    id: "prod_1",
    name: "Madhubani 'Tree of Life'",
    artisanName: "Rina Devi",
    description: "An intricate Madhubani painting depicting the 'Tree of Life', hand-painted with natural dyes on handmade paper, symbolizing vitality and connection.",
    category: "Paintings",
    region: "Bihar",
    price: 2800,
    image: {
      src: "https://res.cloudinary.com/dpkhf4cf5/image/upload/v1761864747/Screenshot_2025-10-31_041631_el9o3e.png",
      hint: "madhubani painting",
    },
    type: "Paintings",
  },
  {
    id: "prod_2",
    name: "Hand-Woven Banarasi Silk Saree",
    artisanName: "Isha Textiles",
    description: "A luxurious Banarasi silk saree, hand-woven with fine gold zari work in a timeless floral pattern, perfect for festive occasions.",
    category: "Textiles",
    region: "Uttar Pradesh",
    price: 12500,
    image: {
      src: "https://picsum.photos/seed/saree2/600/600",
      hint: "silk saree",
    },
    type: "Textiles",
  },
  {
    id: "prod_3",
    name: "Blue Pottery Ceramic Vase",
    artisanName: "Jaipur Blue Pottery",
    description: "A stunning ceramic vase crafted in the iconic Jaipur Blue Pottery style, featuring a lead-free glaze and hand-painted floral motifs.",
    category: "Pottery",
    region: "Rajasthan",
    price: 1500,
    image: {
      src: "https://picsum.photos/seed/pottery3/600/600",
      hint: "blue pottery",
    },
    type: "Pottery",
  },
  {
    id: "prod_4",
    name: "Terracotta Horse Figurines",
    artisanName: "Panchmura Craft",
    description: "A pair of Bankura horses, the iconic terracotta craft of West Bengal, representing artistic excellence and folk heritage.",
    category: "Pottery",
    region: "West Bengal",
    price: 950,
    image: {
      src: "https://picsum.photos/seed/terracotta4/600/600",
      hint: "terracotta horse",
    },
    type: "Pottery",
  },
  {
    id: "prod_5",
    name: "Pattachitra Scroll Painting",
    artisanName: "Raghurajpur Heritage",
    description: "A traditional Pattachitra scroll painting from Odisha, depicting a mythological scene on a treated cloth canvas with rich, natural colors.",
    category: "Paintings",
    region: "Odisha",
    price: 4200,
    image: {
      src: "https://picsum.photos/seed/pattachitra5/600/600",
      hint: "scroll painting",
    },
    type: "Paintings",
  },
  {
    id: "prod_6",
    name: "Hand-carved Sandalwood Elephant",
    artisanName: "Mysore Carvers",
    description: "An exquisitely hand-carved sandalwood elephant, showcasing the detailed craftsmanship of Mysore artisans. A fragrant and elegant decor piece.",
    category: "Woodwork",
    region: "Karnataka",
    price: 3500,
    image: {
      src: "https://picsum.photos/seed/sandalwood6/600/600",
      hint: "carved elephant",
    },
    type: "Woodwork",
  },
];
